#!/bin/bash

# get_remote_file
# This script copies file from remote unix to local machine
# Author: gyoko

# Check for an argument
if [[ ! $1  ]]; then
    echo "Missing filename argument"
    exit 1
fi

filename="$1"
destination="$PWD"

echo "Trying to get ${filename} from remote server"

scp "s62117@os-server:${filename}" "${destination}"

